config/routes.rb
Rails.application.routes.draw do
  get 'flats/index'
  devise_for :users
  root to: "pages#home"
  get "/uitest", to: "pages#uitest"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/my_applications", to: "property_applications#my_applications", as: :my_applications
  resources :properties do
    resources :property_applications, only: [:index, :new, :create] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :property_applications, only: [:index, :show, :edit, :update, :destroy] do
    resources :bank_references, only: [:index, :new, :create] do
      collection do
        get :tenant_index
      end
    end
    resources :employment_documents, only: [:index, :new, :create, :edit ] do
      collection do
        get :tenant_index
      end
    end
    resources :identifications, only: [:index, :new, :create] do
      collection do
        get :tenant_index
      end
    end
    resources :messages
    resources :property_application_finalize, only: [:index]

    member do
      get :finalize
      patch :set_move_in
    end
  end
  get '/property_applications/:id/lease.pdf', to: 'property_applications#lease', format: false, as: 'lease_pdf'
  resources :identifications, only: [:show, :edit, :update, :destroy] do
    member do
      get :download_pdf
    end
  end
  resources :employment_documents, only:[:destroy, :show, :edit, :update] do
    member do
      get :download_pdf
    end
  end
  resources :bank_references, only:[:destroy, :show, :edit, :update] do
    member do
      get :download_pdf
    end
  end
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :property_applications, dependent: :destroy
  has_one_attached :photo

  def address
    "#{number}, #{street}, #{town}, #{postcode}"
  end
  # GEOCODE SECTION ============================================================
  # tells gem that column that needs to be geocoded is the address, NOTHING else will be geocoded
  geocoded_by :address
  # tells gem to save the changes if it is applied to the following column
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]

  # GET /properties
  def index
    @properties = Property.where(user: current_user)
    # @my_properties = Property.where.not(user: current_user)
    # @property_application = PropertyApplication.find(params[:property_application_id])
  end

  # GET /properties/1
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  def create
    @property = Property.new(property_params)
    @property.user = current_user

    if @property.save
      redirect_to properties_path, notice: "Property was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /properties/1
  def update
    if @property.update(property_params)
      redirect_to properties_path, notice: "Property was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /properties/1
  def destroy
    @property.destroy
    redirect_to properties_path, notice: "Property was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(:number, :street, :town, :postcode, :price_per_month, :availability_date, :photo)
  end
end

app/views/properties/_form.html.erb
<%= simple_form_for(@property) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :street %>
    <%= f.input :town %>
    <%= f.input :postcode %>
    <%= f.input :price_per_month %>
    <%= f.input :availability_date, order: [:day, :month, :year], discard_hour: true, discard_minute: true %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>" class="col">
    <div class="card d-flex justify-content-center" style="width: 18rem; height: 500px">
  <%= link_to property_property_applications_path(property) do %>
      <%= cl_image_tag property.photo.key, width:300, class:"card-img-top"%>
      <div class="card-body">
        <h5 class="card-title"><%= property.number %>, <%= property.street %></h5>
        <p class="card-text"><%= property.town %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">£ <%= property.price_per_month %> pcm</li>
        <% date = property.availability_date < DateTime.now ? " Immediately" : property.availability_date.strftime("%d of %B, %Y")%>
        <li class="list-group-item">Available on  <%= date %></li>
        <li class="list-group-item"><%= property.postcode %></li>
      </ul>
      <div class="card-body edit-delete-icons">
        <%# <%= link_to "", property_property_applications_path(property), class:"fa-solid fa-location-arrow" %>
        <%= link_to "", edit_property_path(property), class:"fa-solid fa-pen-to-square","data-bs-toggle": "tooltip", title: "Edit" %>
        <%= link_to "", property_path(property), class:"fa-solid fa-trash",  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, "data-bs-toggle": "tooltip", title: "Delete" %>
      </div>
  <% end %>
    </div>
</div>

app/views/properties/edit.html.erb
<div class="container">
  <h1>Edit Property</h1>
  <%= render "form", property: @property %>

  <br>

  <div>
    <%= link_to "Back to Properties", properties_path %>
  </div>
</div>

app/views/properties/index.html.erb
<div class="container index-titles my-5">
  <h1>Welcome Back, <%= current_user.first_name %></h1>
</div>


<div class="text-center my-3 asset-banner">
    <h2> Property Listings Dashboard </h2>
    <p> You have <%= @properties.count%> listings </p>
    <%# <%= link_to "New property", new_property_path %>
</div>

<div class="d-flex justify-content-end">
  <div class="my-3" style="margin-right: 35px">
    <a href="<%= new_property_path %>" class= "">
     <strong> + New property <strong>
    </a>
  </div>
</div>


  <div class="dashboard  container d-flex justify-content-center my-5" >
    <div class="card-group d-flex justify-content-left">
      <% @properties.each do |property| %>
          <%= render property %>
          <% property_applications = property.property_applications %>
          <%# if theyre a tenant, ovveride the property_applications %>
          <%# <%property_applications = property_applications.where(user: current_user) if current_user.tenant? %>
          <%# Loop through and display each application %>
          <%# <% property.property_applications.where(user: current_user).each do |pa| %>
            <%# <%= render 'property_applications/property_application', property_application: pa %>
          <%# <% end %>
        <% end %>
    </div>
  </div>




<%# dashboard container d-flex justify-content-center my-5 %>

app/views/properties/new.html.erb
<h2 class="mt-4 d-flex justify-content-center">Add a new property</h2>
<div class="container mt-5">
<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to Properties", properties_path %>
</div>
</div>