config/routes.rb
Rails.application.routes.draw do
  get 'flats/index'
  devise_for :users
  root to: "pages#home"
  get "/uitest", to: "pages#uitest"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/my_applications", to: "property_applications#my_applications", as: :my_applications
  resources :properties do
    resources :property_applications, only: [:index, :new, :create] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :property_applications, only: [:index, :show, :edit, :update, :destroy] do
    resources :bank_references, only: [:index, :new, :create] do
      collection do
        get :tenant_index
      end
    end
    resources :employment_documents, only: [:index, :new, :create, :edit ] do
      collection do
        get :tenant_index
      end
    end
    resources :identifications, only: [:index, :new, :create] do
      collection do
        get :tenant_index
      end
    end
    resources :messages
    resources :property_application_finalize, only: [:index]

    member do
      get :finalize
      patch :set_move_in
    end
  end
  get '/property_applications/:id/lease.pdf', to: 'property_applications#lease', format: false, as: 'lease_pdf'
  resources :identifications, only: [:show, :edit, :update, :destroy] do
    member do
      get :download_pdf
    end
  end
  resources :employment_documents, only:[:destroy, :show, :edit, :update] do
    member do
      get :download_pdf
    end
  end
  resources :bank_references, only:[:destroy, :show, :edit, :update] do
    member do
      get :download_pdf
    end
  end
end

app/models/bank_reference.rb
class BankReference < ApplicationRecord
  belongs_to :property_application
  has_one_attached :pdf
  validates :name, presence: true
  validates :issue_date, presence: true
  validates :pdf, presence: true
end

app/controllers/bank_references_controller.rb
require 'open-uri'

class BankReferencesController < ApplicationController
  # GET /property_applications/:property_application_id/bank_references/new
  def index
    @application = PropertyApplication.find(params[:property_application_id])
    @all = BankReference.all
    @b_ref = @all.where(property_application_id: @application)
    # raise
    # @identifications = @all.where(property_application.user.email = current
  end

  def tenant_index
    @application = PropertyApplication.find(params[:property_application_id])
    @bank_refs = BankReference.where(property_application: @application)
  end

  def new
    @application = PropertyApplication.find(params[:property_application_id])
    @bank_reference = BankReference.new
  end

  def edit
    @application = PropertyApplication.find(params[:property_application_id])
    @bank_reference = BankReference.find(params[:id])
  end
# / CODE BEFORE REPLICA

  # def create
  #   @application = PropertyApplication.find(params[:property_application_id])
  #   @bank_reference = BankReference.new(bank_reference_params)
  #   @bank_reference.property_application = @application
  #   @bank_reference.status = "Complete"

  #   if @bank_reference.save!
  #     redirect_to property_application_path(@application.id), format: :html, notice: "Bank Reference page was successfully updated."
  #     # redirect_to action: "show", parent_id: @application.id, id: @bank_reference.id
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  # / CODE AFTER REPLICA
  def create
    @application = PropertyApplication.find(params[:property_application_id])
    @bank_reference = BankReference.new(bank_reference_params)
    @bank_reference.property_application = @application

    if @bank_reference.save
      redirect_to tenant_index_property_application_bank_references_path(@application), notice: "Bank Reference page was successfully updated."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /identification/1
  # def update
  #   if @property.update(property_params)
  #     redirect_to properties_path, notice: "Property was successfully updated."
  #   else
  #     render :edit, status: :unprocessable_entity
  #   end
  # end

  # PATCH/PUT /identification/1
  def update
    @bank_reference = BankReference.find(params[:id])
    @application = @bank_reference.property_application
    if @bank_reference.update(bank_reference_params)
      redirect_to property_application_path(@application), notice: "Bank Reference was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def download_pdf
    @bank_reference = BankReference.find(params[:id])
    blob = @bank_reference.pdf.attachment.blob
    url = Cloudinary::Utils.cloudinary_url(blob.key)

    # Send the file to the user
    data = URI.open(url)
    send_data data.read, type: blob.content_type, filename: blob.filename.to_s, disposition: 'attachment'
  end
  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_bank_reference
  #   @application = PropertyApplication.find(params[:property_application_id])
  #   @property = @application.property
  # end

  def bank_reference_params
    params.require(:bank_reference).permit(:name, :surname, :issue_date, :expiration_date, :pdf)
  end
end

app/views/bank_references/_form.html.erb
<% model = @bank_reference.id.present? ? @bank_reference : [@application, @bank_reference] %>
<%= simple_form_for model do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%# <%= f.input :surname %>
    <%= f.input :issue_date, as: :string, input_html: { data: { controller: 'flatpickr' } }%>
    <%# <%= f.input :expiration_date %>
    <%= f.input :pdf, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bank_references/_idb.html.erb
<%# <% @b_ref.each do |b_ref| %>
<%# <div class="mb-3" style="border: 1px solid black;"> %>
  <%# <%= b_ref.name %>
<%# </div> %>
<%# <% end %>
<%= turbo_frame_tag dom_id(id) do %>
  <div class="mb-3 frame">
    <div class="frame-content">
      <div class="text-content">
        <p><strong>Bank Name:</strong> <%= id.name %></p>
        <% if id.issue_date.present? %>
          <p><strong>Issue Date</strong> <%= id.issue_date.strftime("%d/%m/%Y") %></p>
        <% end %>
        <%#= link_to "Delete", identification_path(id.property_application), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
        <%= link_to "", edit_bank_reference_path(id), class:"fa-solid fa-pen-to-square","data-bs-toggle": "tooltip", title: "Edit"%>
      </div>
      <div class="image-content">
        <%= cl_image_tag(id.pdf.key, :transformation=>[{:width=>350, :crop=>"scale"},
    {:fetch_format => :png}
    ])%>
      </div>
    </div>
  </div>
<% end %>

app/views/bank_references/create.turbo_stream.erb
<%= turbo_stream.prepend dom_id(@application, :ids), partial: 'bank_references/id', locals: { id: @bank_reference }  %>
<%= turbo_stream.update 'new_id' do %>
  <%# Replace with nothing %>
<% end %>

app/views/bank_references/edit.html.erb
<h1>Edit Identification</h1>

<%= turbo_frame_tag dom_id(@bank_reference) do %>
  <div class="mb-3 frame">
    <div class="frame-content">
      <div class="text-content">
        <p><strong>ID Name:</strong> <%= @bank_reference.name %></p>
        <p><strong>Issue Date</strong> <%= @bank_reference.issue_date.strftime("%d/%m/%Y") %></p>
        <p><strong>Expiry Date</strong> <%= @bank_reference.expiration_date.strftime("%d/%m/%Y") %></p>
        <%= link_to "Delete", property_application_bank_references_path(@bank_reference), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

          <%= render "form", identification: @bank_reference %>
          <%= link_to "Cancel", property_application_path(@identification.property_application) %>
      </div>
      <div class="image-content">
        <%= cl_image_tag(@bank_reference.pdf.key, :transformation=>[{:width=>350, :crop=>"scale"},
    {:fetch_format => :jpeg}
    ])%>
      </div>
    </div>
  </div>
<% end %>

app/views/bank_references/index.html.erb
<div class="asset-banner my-5">
  <h1>Applicant Banking Reference</h1>
</div>
<div style="display: flex; justify-content: center; align-items: center;">
  <div class="col-8">
      <div style="display: flex">
        <div class="col-8">
          <p>It's important to have sight of an applicants banking reference to they have financial standing for ongoing payments and to protect your clients' interests. Here are some key things to look out for:</p>
          <ol>
            <li>Financial Stability</li>
            <li>Verification of Identity: A bank reference helps verify the tenant's identity.</li>
            <li>Debt History: A bank reference may reveal any outstanding debts or financial issues. </li>
            <li>Confirmation of Income: A bank reference can provide evidence of a tenant's income. </li>
            <li>Fraud Prevention: Requesting a bank reference can help mitigate the risk of rental fraud. </li>
          </ol>
        </div>
        <div class="col-4">
        <img src="https://res.cloudinary.com/dbwm281qa/image/upload/v1687446387/Bank_image_copy_u6lmpe.png" style="width:100%">
        </div>
      </div>
      <br>
      <h4 style="color: #22577A;">Documents available for review:</h4>
      <br>
      <div class="card-group">
        <% @b_ref.each do |b_ref| %>
        <div class="card">
          <div class="card-body bankdocs">
            <p class="card-title bankref"><%= b_ref.name %></p>
            <% if b_ref.issue_date.present? %>
              <p class="card-text bankref">Issued on :<%= b_ref.issue_date.strftime("%d/%m/%Y") %></p>
            <% end %>
            <%= link_to "Download", download_pdf_bank_reference_path(b_ref), class: "btn btn-primary" %>

            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Review Bank Reference
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-fullscreen">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Banking Reference</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%# THIS NEEDS TO BE WORKED ON NEED CL URL %>
                    <embed src="<%= cloudinary_url(b_ref.pdf.key) %>" width="100%" style="height: calc(100vh - 150px);" type="application/pdf">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>


              <script src=
              "https://code.jquery.com/jquery-3.3.1.slim.min.js"
                    integrity=
              "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                    crossorigin="anonymous">
                </script>
                <script src=
              "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                    integrity=
              "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                    crossorigin="anonymous">
                </script>
                <script src=
              "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                    integrity=
              "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                    crossorigin="anonymous">
                </script>
            </div>
            </div>


          <%#= link_to "Delete ID", property_path(id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

app/views/bank_references/new.html.erb
<%= render "form", bank_reference: @bank_reference %>

<main class="container">
  <%= link_to sanitize("&larr; Back to Dashboard"), property_application_path(params[:property_application_id]) %>

  <%# <%= turbo_frame_tag "second_frame" do %>
  <div class="header">
    <h1>New Bank Reference</h1>
  </div>

  <%= turbo_frame_tag "new_b" do %>
    <%= render "form", bank_reference: @bank_reference %>
    <%= link_to 'Cancel', property_application_path(@application) %>
  <% end %>

</main>

<%# NEW IDEA %>
  <%= turbo_frame_tag :application_step do %>
    <%= render 'property_applications/steps', current_step: 3, property_application: @application %>
    <%= render "form", identifications: @identification %>
    <%= link_to 'Cancel', tenant_index_property_application_identifications_path(@application) %>
  <% end %>
<%# END NEW IDEA %>

app/views/bank_references/show.html.erb
<h1>Bank Reference</h1>

<%= render "form", property: @bank_reference %>

<br>

<div>
  <%= link_to "Back to Application", property_application_path(params[:property_application_id]) %>
</div>

app/views/bank_references/tenant_index.html.erb
<%= turbo_frame_tag :application_step do %>
  <%= render 'property_applications/steps', current_step: 3, property_application: @application %>
  <br>
  <p class="steptext"> Using the button and form below, please upload at least a bank statement from the past 3 months demostrating that you have sufficent fund for deposit and initial rental payment. </p>
  <br>
  <%= link_to "Upload Bank Statement",
    new_property_application_bank_reference_path(@application),
    class: "btn btn-lg btn-primary btn-banner m-0 mb-3",
    style: "width: 100%" %>
  <br>
  <br>
  <% @bank_refs.each do |id| %>
    <%= render 'bank_references/idb', id: id %>
  <% end %>
<% end %>