config/routes.rb
Rails.application.routes.draw do
  get 'flats/index'
  devise_for :users
  root to: "pages#home"
  get "/uitest", to: "pages#uitest"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/my_applications", to: "property_applications#my_applications", as: :my_applications
  resources :properties do
    resources :property_applications, only: [:index, :new, :create] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :property_applications, only: [:index, :show, :edit, :update, :destroy] do
    resources :bank_references, only: [:index, :new, :create] do
      collection do
        get :tenant_index
      end
    end
    resources :employment_documents, only: [:index, :new, :create, :edit ] do
      collection do
        get :tenant_index
      end
    end
    resources :identifications, only: [:index, :new, :create] do
      collection do
        get :tenant_index
      end
    end
    resources :messages
    resources :property_application_finalize, only: [:index]

    member do
      get :finalize
      patch :set_move_in
    end
  end
  get '/property_applications/:id/lease.pdf', to: 'property_applications#lease', format: false, as: 'lease_pdf'
  resources :identifications, only: [:show, :edit, :update, :destroy] do
    member do
      get :download_pdf
    end
  end
  resources :employment_documents, only:[:destroy, :show, :edit, :update] do
    member do
      get :download_pdf
    end
  end
  resources :bank_references, only:[:destroy, :show, :edit, :update] do
    member do
      get :download_pdf
    end
  end
end

app/models/identification.rb
class Identification < ApplicationRecord
  belongs_to :property_application
  validates :name, presence: true
  validates :expiration_date, presence: true
  validates :pdf, presence: true
  has_one_attached :pdf, dependent: :destroy
end

app/controllers/identifications_controller.rb
require 'open-uri'

class IdentificationsController < ApplicationController
  before_action :set_property_application, only: %i[ index tenant_index new create]

  def index
    @all = Identification.all
    @id = @all.where(property_application_id: @application)
    # raise
    # @identifications = @all.where(property_application.user.email = current
  end

  def tenant_index
    @ids = Identification.where(property_application: @application)
  end

  def new
    @identification = Identification.new
  end

  # GET /identifications/:id/edit
  def edit
    @identification = Identification.find(params[:id])
  end

  # POST /identification
  def create
    @identification = Identification.new(identification_params)
    @identification.property_application = @application

    # respond_to do |format|
    if @identification.save!
      # redirect_to property_application_path(@property), notice: "Identification page was successfully updated."
      # format.turbo_stream
      redirect_to  tenant_index_property_application_identifications_path(@application), notice: "Identification document was successfully saved." # -> path to the show page for employment document
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @identification.destroy
    redirect_to properties_path, notice: "Indentification documents were successfully destroyed.", status: :see_other
  end


  # PATCH/PUT /identification/1
  def update
    @identification = Identification.find(params[:id])
    @application = @identification.property_application
    if @identification.update(identification_params)
      redirect_to property_application_path(@application), notice: "Identification was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def download_pdf
    @identification = Identification.find(params[:id])
    blob = @identification.pdf.attachment.blob
    url = Cloudinary::Utils.cloudinary_url(blob.key)

    # Send the file to the user
    data = URI.open(url)
    send_data data.read, type: blob.content_type, filename: blob.filename.to_s, disposition: 'attachment'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property_application
    @application = PropertyApplication.find(params[:property_application_id])
    @property = @application.property
  end

  def identification_params
    params.require(:identification).permit(:name, :issue_date, :expiration_date, :pdf)
  end
end

app/views/identifications/_form.html.erb
<% model = @identification.id.present? ? @identification : [@application, @identification] %>
<%= simple_form_for model do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :issue_date,  as: :string, input_html: { data: { controller: 'flatpickr' } }%>
    <%= f.input :expiration_date, as: :string, input_html: { data: { controller: 'flatpickr' } } %>
    <%= f.input :pdf, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/identifications/_id.html.erb
<%= turbo_frame_tag dom_id(id) do %>
  <div class="mb-3 frame">
    <div class="frame-content">
      <div class="text-content">
        <p><strong>Name of ID Document:</strong> <%= id.name %></p>
        <% if id.issue_date.present? %>
          <p><strong>Issued on :</strong> <%= id.issue_date.strftime("%d/%m/%Y") %></p>
        <% end %>
        <% if id.expiration_date.present? %>
          <p><strong>Expires on </strong> <%= id.expiration_date.strftime("%d/%m/%Y") %></p>
        <% end %>
        <%#= link_to "Delete", identification_path(id.property_application), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

          <%= link_to "", edit_identification_path(id), class:"fa-solid fa-pen-to-square","data-bs-toggle": "tooltip", title: "Edit"%>
      </div>
      <div class="image-content">
        <%= cl_image_tag(id.pdf.key, :transformation=>[{:width=>350, :crop=>"scale"},
    {:fetch_format => :png}
    ])%>
      </div>
    </div>
  </div>
<% end %>

app/views/identifications/create.turbo_stream.erb
<%= turbo_stream.prepend dom_id(@application, :ids), partial: 'identifications/id', locals: { id: @identification }  %>
<%= turbo_stream.update 'new_id' do %>
  <%# Replace with nothing %>
<% end %>

app/views/identifications/edit.html.erb
<h1>Edit Identification</h1>

<%= turbo_frame_tag dom_id(@identification) do %>
  <div class="mb-3 frame">
    <div class="frame-content">
      <div class="text-content">
        <p><strong>ID Name:</strong> <%= @identification.name %></p>
        <p><strong>Issue Date</strong> <%= @identification.issue_date %></p>
        <p><strong>Expiry Date</strong> <%= @identification.expiration_date %></p>
        <%= link_to "Delete", identification_path(@identification), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

          <%= render "form", identification: @identification %>
          <%= link_to "Cancel", property_application_path(@identification.property_application) %>
      </div>
      <div class="image-content">
        <%= cl_image_tag(@identification.pdf.key, :transformation=>[{:width=>350, :crop=>"scale"},
    {:fetch_format => :jpeg}
    ])%>
      </div>
    </div>
  </div>
<% end %>

app/views/identifications/index.html.erb
<div class="asset-banner my-5">
  <h1>Applicant Identification Documentation</h1>
</div>
<div style="display: flex; justify-content: center; align-items: center;">
  <div class="col-8">
      <div style="display: flex">
        <div class="col-8">
          <p>It's important to verify the identification of potential applicants to ensure their legitimacy and protect your clients' interests. Here are some key things to look out for when reviewing applicant identification:</p>
          <ol>
            <li>Government-issued ID: Check if the applicant has provided a valid government-issued identification document</li>
            <li>Authenticity features: Familiarize yourself with the security features of various identification documents.</li>
            <li>Matching information: Cross-reference the information provided other forms and applications submitted by the applicant. </li>
            <li>Clear photo: Examine the photo on the identification document carefully. </li>
            <li>Trust your instincts!</li>
          </ol>
        </div>
        <div class="col-4">
        <img src="https://cdn.onlinewebfonts.com/svg/img_52066.png" style="width:100%">
        </div>
      </div>
      <br>
      <h4 style="color: #22577A;">Documents available for review:</h4>
      <br>
      <% if @id.empty? %>
        <p> Waiting for the applicant to upload information. </p>
      <% end %>
      <div class="card-group">
        <% @id.each do |id| %>
        <div class="card">
          <div class="card-body bankdocs">
            <h5 class="card-title bankref"><%= id.name %></h5>
            <% if id.issue_date.present? %>
              <p class="card-text">Issued on :<%= id.issue_date.strftime("%d/%m/%Y") %></p>
            <% end %>
            <% if id.expiration_date.present? %>
              <p class="card-text"><small class="text-muted"> Expires on :<%= id.expiration_date.strftime("%d/%m/%Y") %></small></p>
            <% end %>
          </div>
            <%= link_to "Download", download_pdf_identification_path(id) %>
            <%# this one works, below for preview of image  %>
            <div class="image-content">
              <%= cl_image_tag(id.pdf.key, :transformation=>[{:width=>350, :crop=>"scale"},
                {:fetch_format => :png}
                ])%>
            </div>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Review ID
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-fullscreen">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Identification Document</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%# THIS NEEDS TO BE WORKED ON NEED CL URL %>
                    <embed src="<%= cloudinary_url(id.pdf.key) %>" width="100%" style="height: calc(100vh - 150px);" type="application/pdf">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

              <script src=
              "https://code.jquery.com/jquery-3.3.1.slim.min.js"
                    integrity=
              "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                    crossorigin="anonymous">
                </script>
                <script src=
              "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                    integrity=
              "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                    crossorigin="anonymous">
                </script>
                <script src=
              "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                    integrity=
              "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                    crossorigin="anonymous">
                </script>
            </div>

          <%if current_user == id.property_application.user %>
            <%= link_to "Amend ID", edit_property_application_identification_path(id.property_application, id.id), class:"card-link" %>
          <% end %>
          <%#= link_to "Delete ID", property_path(id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/identifications/new.html.erb
<%# <%= <h1>New Identification Form</h1> %>

<%= render "form", identifications: @identification %>

<%# <div> %>
  <%# <%= link_to "Back to Application", property_application_path(params[:property_application_id]) %> %>
<%# </div> %>

<main class="container">
  <%= link_to sanitize("&larr; Back to Dashboard"), property_application_path(params[:property_application_id]) %>

  <%# <%= turbo_frame_tag "second_frame" do %>
  <div class="header">
    <h1>New Identification</h1>
  </div>

  <%= turbo_frame_tag "new_id" do %>
    <%= render "form", identifications: @identification %>
    <%= link_to 'Cancel', property_application_path(@application) %>
  <% end %>

  <%# NEW IDEA %>
    <%= turbo_frame_tag :application_step do %>
      <%= render 'property_applications/steps', current_step: 1, property_application: @application %>
      <%= render "form", identifications: @identification %>
      <%= link_to 'Cancel', tenant_index_property_application_identifications_path(@application) %>
    <% end %>
  <%# END NEW IDEA %>

</main>

app/views/identifications/show.html.erb
<h1>Identification</h1>

<%= render "form", property: @identification %>

<br>

<div>
  <%= link_to "Back to Application", property_application_path(params[:property_application_id]) %>
</div>

app/views/identifications/tenant_index.html.erb
<%= turbo_frame_tag :application_step do %>
  <%= render 'property_applications/steps', current_step: 1, property_application: @application %>
  <br>
  <p class="steptext"> Using the button and form below, please upload at least one form of personal identification this can be any of the following: Passport or Drivers Licence. </p>
  <br>
  <%= link_to "Upload Personal Identification",
    new_property_application_identification_path(@application),
    class: "btn btn-lg btn-primary btn-banner m-0 mb-3",
    style: "width: 100%" %>
  <br>
  <br>
  <% @ids.each do |id| %>
    <%= render 'identifications/id', id: id %>
  <% end %>
<% end %>