config/routes.rb
Rails.application.routes.draw do
  get 'flats/index'
  devise_for :users
  root to: "pages#home"
  get "/uitest", to: "pages#uitest"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/my_applications", to: "property_applications#my_applications", as: :my_applications
  resources :properties do
    resources :property_applications, only: [:index, :new, :create] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :property_applications, only: [:index, :show, :edit, :update, :destroy] do
    resources :bank_references, only: [:index, :new, :create] do
      collection do
        get :tenant_index
      end
    end
    resources :employment_documents, only: [:index, :new, :create, :edit ] do
      collection do
        get :tenant_index
      end
    end
    resources :identifications, only: [:index, :new, :create] do
      collection do
        get :tenant_index
      end
    end
    resources :messages
    resources :property_application_finalize, only: [:index]

    member do
      get :finalize
      patch :set_move_in
    end
  end
  get '/property_applications/:id/lease.pdf', to: 'property_applications#lease', format: false, as: 'lease_pdf'
  resources :identifications, only: [:show, :edit, :update, :destroy] do
    member do
      get :download_pdf
    end
  end
  resources :employment_documents, only:[:destroy, :show, :edit, :update] do
    member do
      get :download_pdf
    end
  end
  resources :bank_references, only:[:destroy, :show, :edit, :update] do
    member do
      get :download_pdf
    end
  end
end

app/models/employment_document.rb
class EmploymentDocument < ApplicationRecord
  belongs_to :property_application
  validates :company_name, presence: true
  validates :date, presence: true
  validates :pdf, presence: true
  has_one_attached :pdf
end

app/controllers/employment_documents_controller.rb
require 'open-uri'

class EmploymentDocumentsController < ApplicationController
  before_action :set_property_application, only: %i[index tenant_index new create]

  def index
    # @employment_documents = EmploymentDocument.all
    @all = EmploymentDocument.all
    @e_ref = @all.where(property_application_id: @property_application)
  end

  def tenant_index
    @employment_documents = EmploymentDocument.where(property_application: @property_application)
  end

  # GET /property_applications/:property_application_id/employment_documents/new
  def new
    @employment_document = EmploymentDocument.new
  end

  # POST /property_applications/:property_application_id/employment_documents
  def create
    @employment_document = EmploymentDocument.new(employment_document_params)
    # property application id is needed for the simple form
    # save the property id to the left side
    @employment_document.property_application_id = @property_application.id

    if @employment_document.save!
      # redirect_to  property_application_path(@property_application.id) -> this line path to property application

      # stuck here, cannot find the right id
      redirect_to  tenant_index_property_application_employment_documents_path(@property_application), notice: "Employment document was successfully saved." # -> path to the show page for employment document
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /employment_documents/:id
  def show
    @employment_document = EmploymentDocument.find(params[:id])
    @property_application = @employment_document.property_application
  end

  def edit
    @employment_document = EmploymentDocument.find(params[:id])
  end

  def update
    @employment_document = EmploymentDocument.find(params[:id])
    @property_application = @employment_document.property_application
    if @employment_document.update(employment_document_params)
      redirect_to property_application_path(@property_application.id), notice: "Employment document was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employment_document = EmploymentDocument.find(params[:id])
    @property_application = @employment_document.property_application
    @employment_document.destroy
    redirect_to property_application_path(@property_application.id), notice: "Employment document was successfully destroyed.", status: :see_other
  end

  def download_pdf
    @employment_document = EmploymentDocument.find(params[:id])
    blob = @employment_document.pdf.attachment.blob
    url = Cloudinary::Utils.cloudinary_url(blob.key)

    # Send the file to the user
    data = URI.open(url)
    send_data data.read, type: blob.content_type, filename: blob.filename.to_s, disposition: 'attachment'
  end

  private

  def set_property_application
    @property_application = PropertyApplication.find(params[:property_application_id])
  end

  def employment_document_params
    params.require(:employment_document).permit(:company_name, :date, :status, :property_application_id, :pdf)
  end

end

app/views/employment_documents/_form.html.erb
<%# EMPLOYMENT FORM %>

<% model = @employment_document.id.present? ? @employment_document : [@property_application, @employment_document] %>
<%= simple_form_for model do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :company_name %>
    <%= f.input :date, as: :string, input_html: { data: { controller: 'flatpickr' } } %>
    <%#= f.input :status %>
    <%= f.input :pdf, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employment_documents/_ide.html.erb
<%= turbo_frame_tag dom_id(id) do %>
  <div class="mb-3 frame">
    <div class="frame-content">
      <div class="text-content">
        <p><strong>Company Name:</strong> <%= id.company_name %></p>
        <% if id.date.present? %>
          <p><strong>Issued on</strong> <%= id.date.strftime("%d/%m/%Y") %></p>
        <% end %>
        <%#= link_to "Delete", identification_path(id.property_application), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

          <%= link_to "", edit_employment_document_path(id), class:"fa-solid fa-pen-to-square","data-bs-toggle": "tooltip", title: "Edit"%>
      </div>
      <div class="image-content">
        <%= cl_image_tag(id.pdf.key, :transformation=>[{:width=>350, :crop=>"scale"},
    {:fetch_format => :png}
    ])%>
      </div>
    </div>
  </div>
<% end %>

app/views/employment_documents/create.turbo_stream.erb
<%= turbo_stream.prepend dom_id(@employment_document, :ids), partial: 'employment_documents/ide', locals: { id: id }  %>
<%= turbo_stream.update 'new_ide' do %>
  <%# Replace with nothing %>
<% end %>

app/views/employment_documents/edit.html.erb
<h1>Edit page for employment document</h1>
<%= turbo_frame_tag dom_id(@employment_document) do %>
  <%= simple_form_for [@property_application, @employment_document] do |f| %>
    <%= f.input :company_name %>
    <%= f.input :date, as: :string, input_html: { data: { controller: 'flatpickr' } }%>
    <%= f.input :status %>
    <%= f.input :pdf, as: :file %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/employment_documents/index.html.erb
<div class="asset-banner my-5">
  <h1>Applicant Employment Documentation</h1>
</div>
<div style="display: flex; justify-content: center; align-items: center;">
  <div class="col-8">
      <div style="display: flex">
        <div class="col-8">
          <p>When reviewing employment references consider the following to ensure they are capable of managing ongoing commitments:</p>
          <ol>
            <li>Relevance: Assess the relevance of the reference</li>
            <li>Relationship to the Candidate: Evaluate the nature of the relationship between the reference and the candidate. </li>
            <li>Credibility and Trustworthiness.</li>
            <li>Reliability and Contact Information: Ensure that the reference's contact information</li>
          </ol>
        </div>
        <div class="col-4">
        <img src="https://res.cloudinary.com/dbwm281qa/image/upload/v1687446398/employmentref_hwhz2r.png" style="width:100%">
        </div>
      </div>
      <br>
      <h4 style="color: #22577A;">Employment documents (if applicable) for review:</h4>
      <br>
      <div class="card-group">
        <% @e_ref.each do |employment_document| %>
        <div class="card">
          <div class="card-body bank docs">
            <h5 class="card-title bankref">Company name: <%= employment_document.company_name %></h5>
            <% if employment_document.date.present? %>
              <p class="card-text"> Issued on <%= employment_document.date.strftime("%d/%m/%Y") %></p>
            <% end %>
          </div>
            <%# new code %>
            <%= link_to "Download", download_pdf_employment_document_path(employment_document) %>
            <%# this one works, below for preview of image.... not pdf yet  %>
            <%# <div class="image-content">
              <%= cl_image_tag(employment_document.pdf.key, :transformation=>[{:width=>150, :crop=>"scale"},
                {:fetch_format => :png}
                ])%>
            <%# </div>  %>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Review Employment
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-fullscreen">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Employment Document</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%# THIS NEEDS TO BE WORKED ON NEED CL URL %>
                    <embed src="<%= cloudinary_url(employment_document.pdf.key) %>" width="100%" style="height: calc(100vh - 150px);" type="application/pdf">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

            <%# <%= cl_image_tag id.pdf.key, class:"card-img-bottom" %>
          <%if current_user == employment_document.property_application.user %>
            <%= link_to "Delete document", employment_document_path(employment_document.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <% end %>
          <%#= link_to "Delete ID", property_path(id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%# <h1>Index page for employment documents</h1>
<% @employment_documents.each do |employment_document| %>
  <%# <div>
    <ul>
      <li>Company name: <strong><%= employment_document.company_name %>
      <%# <p>Created date: </p> <strong><%= employment_document.date %>
      <%# <p>Status: </p> <strong><%= employment_document.status %>
      <%# <%= link_to "Delete document", employment_document_path(employment_document.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <%# </ul></strong> %>
  <%# </div> %>
<%# <% end %>

app/views/employment_documents/new.html.erb
<%# <%= <h1>New Employment Form</h1> %>

<%= render "form", employment_document: @employment_document %>

<%# <div class="container">
  <%= simple_form_for [@property_application, @employment_document] do |f| %>
    <%# <%= f.input :company_name %>
    <%# <%= f.input :date %>
    <%# <%= f.input :status %>
    <%# <%= f.input :pdf, as: :file %>
    <%# <%= f.button :submit, class: "btn btn-primary" %>
  <%# <% end %>
<%# </div> %>

<main class="container">
  <%= link_to sanitize("&larr; Back to Dashboard"), property_application_path(params[:property_application_id]) %>

  <%# <%= turbo_frame_tag "second_frame" do %>
  <div class="header">
    <h1>New Employment Reference</h1>
  </div>

  <%= turbo_frame_tag "new_e" do %>
    <%= render "form", employment_document: @employment_document %>
    <%= link_to 'Cancel', property_application_path(@property_application) %>
  <% end %>

 <%# NEW IDEA %>
    <%= turbo_frame_tag :application_step do %>
      <%= render 'property_applications/steps', current_step: 2, property_application: @property_application %>
      <%= render "form", identifications: @identification %>
      <%= link_to 'Cancel', tenant_index_property_application_employment_documents_path(@property_application) %>
    <% end %>
  <%# END NEW IDEA %>

</main>

app/views/employment_documents/show.html.erb
<p>Review your document details: </p>
<li><p>Company name: <%= @employment_document.company_name %></p></li>
<li><p>Created date: <%= @employment_document.date.strftime("%d/%m/%Y") %></p></li>
<li>document status: <%= @employment_document.status %></p></li>
<%= link_to "Edit document", edit_employment_document_path(@employment_document.id)%>
<%= link_to "Delete document", employment_document_path(@employment_document.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

<%= link_to "Return to property application", property_application_path(@property_application.id)%>

app/views/employment_documents/tenant_index.html.erb
<%= turbo_frame_tag :application_step do %>
  <%= render 'property_applications/steps', current_step: 2, property_application: @property_application %>
  <br>
  <p class="steptext"> Using the button and form below, please upload proof of employment in the form of employers reference, payslip or P45 form </p>
  <br>
  <%= link_to "Upload Employment Reference",
    new_property_application_employment_document_path(@property_application),
    class: "btn btn-lg btn-primary btn-banner m-0 mb-3",
    style: "width: 100%" %>
  <br>
  <br>
  <% @employment_documents.each do |emp_doc| %>
    <%= render 'employment_documents/ide', id: emp_doc %>
    <%# <p>Employment Document: <%= emp_doc.id %>
  <% end %>
<% end %>